[package]
name = "rust"
version = "0.0.0"
authors = ["David Rieser <david.w.rieser@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
